# Generated by Django 5.1.2 on 2024-10-09 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ODMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_stage', models.CharField(max_length=255)),
                ('to_stage', models.CharField(max_length=255)),
                ('passenger_count', models.IntegerField()),
            ],
        ),
    ]
